---

- hosts: all
  become: yes
  tasks:
    - name: Update packages list
      pacman: update_cache=yes
      when: ansible_os_family == 'Archlinux'

    - name: List packages to upgrade (1/2)
      shell: pacman -Syup
      register: updates
      changed_when: False
      when: ansible_os_family == 'Archlinux'

    - name: List packages to upgrade (2/2)
      debug: msg="{{ updates.stdout_lines | count }} packages to upgrade ({{ updates.stdout_lines | join(', ') }})"
      when: (ansible_os_family == 'Archlinux' and updates.stdout_lines)

    - name: Upgrade packages
      pacman: upgrade=yes
      when: ansible_os_family == 'Archlinux'

    - name: List new configuration files (1/2)
      shell: find /etc/ -name *.pacnew
      register: pacnew
      changed_when: False
      when: ansible_os_family == 'Archlinux'

    - name: List new configuration files (2/2)
      debug: msg="{{ pacnew.stdout_lines | count }} config files to merge ({{ pacnew.stdout_lines | join (', ') }})"
      when: (ansible_os_family == 'Archlinux' and pacnew.stdout_lines)
