---
- hosts: all
  roles:
    - cloudalchemy.node-exporter
  vars:
      node_exporter_web_listen_address: "0.0.0.0:9100"
      node_exporter_version: 0.17.0
      node_exporter_enabled_collectors:
        - "systemd"
        - "textfile"
      node_exporter_textfile_dir: "/var/lib/node_exporter"

